# Form implementation generated from reading ui file 'C:\Users\nesto\OneDrive - Universidad de la Sabana\Diseño proyecto final\Diseno\DAgregarCategoria.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AgregarCategorias(object):
    def setupUi(self, AgregarCategorias):
        AgregarCategorias.setObjectName("AgregarCategorias")
        AgregarCategorias.resize(552, 490)
        self.centralwidget = QtWidgets.QWidget(parent=AgregarCategorias)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 130, 431, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Nombre = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Nombre.setMaxLength(25)
        self.Nombre.setObjectName("Nombre")
        self.gridLayout.addWidget(self.Nombre, 3, 1, 1, 1)
        self.PBSalir = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBSalir.setObjectName("PBSalir")
        self.gridLayout.addWidget(self.PBSalir, 4, 0, 1, 1)
        self.SBCodigo = QtWidgets.QSpinBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SBCodigo.setFont(font)
        self.SBCodigo.setMaximum(999999999)
        self.SBCodigo.setObjectName("SBCodigo")
        self.gridLayout.addWidget(self.SBCodigo, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.PBAgregar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBAgregar.setObjectName("PBAgregar")
        self.gridLayout.addWidget(self.PBAgregar, 4, 1, 1, 1)
        self.LTitulo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.LTitulo.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        self.gridLayout.addWidget(self.LTitulo, 0, 0, 1, 3)
        AgregarCategorias.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=AgregarCategorias)
        self.statusbar.setObjectName("statusbar")
        AgregarCategorias.setStatusBar(self.statusbar)

        self.retranslateUi(AgregarCategorias)
        QtCore.QMetaObject.connectSlotsByName(AgregarCategorias)

    def retranslateUi(self, AgregarCategorias):
        _translate = QtCore.QCoreApplication.translate
        AgregarCategorias.setWindowTitle(_translate("AgregarCategorias", "MainWindow"))
        self.PBSalir.setText(_translate("AgregarCategorias", "Salir"))
        self.label.setText(_translate("AgregarCategorias", "Codigo Nuevo"))
        self.label_2.setText(_translate("AgregarCategorias", "Nombre"))
        self.PBAgregar.setText(_translate("AgregarCategorias", "Agregar"))
        self.LTitulo.setText(_translate("AgregarCategorias", "Agregar Categorias"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarCategorias = QtWidgets.QMainWindow()
    ui = Ui_AgregarCategorias()
    ui.setupUi(AgregarCategorias)
    AgregarCategorias.show()
    sys.exit(app.exec())
