# Form implementation generated from reading ui file 'C:\Users\nesto\OneDrive - Universidad de la Sabana\Diseño proyecto final\Diseno\DAgregarCentro.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AgregarCentros(object):
    def setupUi(self, AgregarCentros):
        AgregarCentros.setObjectName("AgregarCentros")
        AgregarCentros.resize(552, 490)
        self.centralwidget = QtWidgets.QWidget(parent=AgregarCentros)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 130, 431, 134))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Nombre = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Nombre.setMaxLength(30)
        self.Nombre.setObjectName("Nombre")
        self.gridLayout.addWidget(self.Nombre, 2, 1, 1, 1)
        self.PBSalir = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBSalir.setObjectName("PBSalir")
        self.gridLayout.addWidget(self.PBSalir, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.LTitulo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.LTitulo.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        self.gridLayout.addWidget(self.LTitulo, 0, 0, 1, 3)
        self.Direccion = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Direccion.setMaxLength(45)
        self.Direccion.setObjectName("Direccion")
        self.gridLayout.addWidget(self.Direccion, 3, 1, 1, 1)
        self.PBAgregar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBAgregar.setObjectName("PBAgregar")
        self.gridLayout.addWidget(self.PBAgregar, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.Telefono = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Telefono.setMaxLength(45)
        self.Telefono.setObjectName("Telefono")
        self.gridLayout.addWidget(self.Telefono, 4, 1, 1, 1)
        AgregarCentros.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=AgregarCentros)
        self.statusbar.setObjectName("statusbar")
        AgregarCentros.setStatusBar(self.statusbar)

        self.retranslateUi(AgregarCentros)
        QtCore.QMetaObject.connectSlotsByName(AgregarCentros)

    def retranslateUi(self, AgregarCentros):
        _translate = QtCore.QCoreApplication.translate
        AgregarCentros.setWindowTitle(_translate("AgregarCentros", "MainWindow"))
        self.PBSalir.setText(_translate("AgregarCentros", "Salir"))
        self.label_2.setText(_translate("AgregarCentros", "Nombre"))
        self.LTitulo.setText(_translate("AgregarCentros", "Agregar Centros"))
        self.PBAgregar.setText(_translate("AgregarCentros", "Agregar"))
        self.label_3.setText(_translate("AgregarCentros", "Direccion"))
        self.label_4.setText(_translate("AgregarCentros", "Telefono"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgregarCentros = QtWidgets.QMainWindow()
    ui = Ui_AgregarCentros()
    ui.setupUi(AgregarCentros)
    AgregarCentros.show()
    sys.exit(app.exec())
