# Form implementation generated from reading ui file 'C:\Users\nesto\OneDrive - Universidad de la Sabana\Diseño proyecto final\Diseno\DModificarCategoria.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModificarCategorias(object):
    def setupUi(self, ModificarCategorias):
        ModificarCategorias.setObjectName("ModificarCategorias")
        ModificarCategorias.resize(552, 490)
        self.centralwidget = QtWidgets.QWidget(parent=ModificarCategorias)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 130, 431, 152))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Nombre = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Nombre.setMaxLength(25)
        self.Nombre.setObjectName("Nombre")
        self.gridLayout.addWidget(self.Nombre, 3, 1, 1, 1)
        self.PBSalir = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBSalir.setObjectName("PBSalir")
        self.gridLayout.addWidget(self.PBSalir, 5, 0, 1, 1)
        self.SBCodigo = QtWidgets.QSpinBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SBCodigo.setFont(font)
        self.SBCodigo.setMaximum(999999999)
        self.SBCodigo.setObjectName("SBCodigo")
        self.gridLayout.addWidget(self.SBCodigo, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.LTitulo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.LTitulo.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        self.gridLayout.addWidget(self.LTitulo, 0, 0, 1, 3)
        self.PBAgregar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.PBAgregar.setObjectName("PBAgregar")
        self.gridLayout.addWidget(self.PBAgregar, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.SBCodigoViejo = QtWidgets.QSpinBox(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SBCodigoViejo.setFont(font)
        self.SBCodigoViejo.setMaximum(999999999)
        self.SBCodigoViejo.setObjectName("SBCodigoViejo")
        self.gridLayout.addWidget(self.SBCodigoViejo, 4, 1, 1, 1)
        ModificarCategorias.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ModificarCategorias)
        self.statusbar.setObjectName("statusbar")
        ModificarCategorias.setStatusBar(self.statusbar)

        self.retranslateUi(ModificarCategorias)
        QtCore.QMetaObject.connectSlotsByName(ModificarCategorias)

    def retranslateUi(self, ModificarCategorias):
        _translate = QtCore.QCoreApplication.translate
        ModificarCategorias.setWindowTitle(_translate("ModificarCategorias", "MainWindow"))
        self.PBSalir.setText(_translate("ModificarCategorias", "Salir"))
        self.label.setText(_translate("ModificarCategorias", "Codigo Nuevo"))
        self.label_2.setText(_translate("ModificarCategorias", "Nombre"))
        self.LTitulo.setText(_translate("ModificarCategorias", "Modificar Categorias"))
        self.PBAgregar.setText(_translate("ModificarCategorias", "Modificar"))
        self.label_3.setText(_translate("ModificarCategorias", "Codigo Viejo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModificarCategorias = QtWidgets.QMainWindow()
    ui = Ui_ModificarCategorias()
    ui.setupUi(ModificarCategorias)
    ModificarCategorias.show()
    sys.exit(app.exec())
