# Form implementation generated from reading ui file 'C:\Users\dati2\OneDrive - Universidad de la Sabana\AdmonCentroAdultos\Diseno\DPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 420)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BTerminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BTerminar.setGeometry(QtCore.QRect(260, 350, 619, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BTerminar.setFont(font)
        self.BTerminar.setObjectName("BTerminar")
        self.LTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.LTitulo.setGeometry(QtCore.QRect(110, 30, 617, 33))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(18)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        self.BAc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BAc.setGeometry(QtCore.QRect(10, 90, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BAc.setFont(font)
        self.BAc.setObjectName("BAc")
        self.BAd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BAd.setGeometry(QtCore.QRect(600, 80, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BAd.setFont(font)
        self.BAd.setObjectName("BAd")
        self.BCa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BCa.setGeometry(QtCore.QRect(20, 230, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BCa.setFont(font)
        self.BCa.setObjectName("BCa")
        self.BCe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BCe.setGeometry(QtCore.QRect(610, 220, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BCe.setFont(font)
        self.BCe.setObjectName("BCe")
        self.BIns = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BIns.setGeometry(QtCore.QRect(310, 150, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BIns.setFont(font)
        self.BIns.setObjectName("BIns")
        self.BCon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BCon.setGeometry(QtCore.QRect(330, 300, 341, 42))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BCon.setFont(font)
        self.BCon.setObjectName("BCon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Proyectos de Facultad"))
        self.BTerminar.setText(_translate("MainWindow", "Terminar"))
        self.LTitulo.setText(_translate("MainWindow", "ADMINISTRACIÓN CENTRO ADULTOS"))
        self.BAc.setText(_translate("MainWindow", "Acitividades"))
        self.BAd.setText(_translate("MainWindow", "Adultos"))
        self.BCa.setText(_translate("MainWindow", "Categorias"))
        self.BCe.setText(_translate("MainWindow", "Centros"))
        self.BIns.setText(_translate("MainWindow", "Inscripciones"))
        self.BCon.setText(_translate("MainWindow", "Consultas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
